Check touch
CMU-cabot/cabot-ble-server pull request #20
Opened 2024-04-02 11:02 UTC by miyazakifuki

2024-04-03 15:18 UTC, dsato80 requested changes
少し修正をお願いします。

2024-04-03 15:18 UTC, dsato80 commented on common.py
> +    activity_log("cabot/touch", message)
activity_logはstrを期待しているのでmessageは渡すまえにstrにしてください。

2024-04-03 15:18 UTC, dsato80 commented on common.py
> +    activity_log("cabot/touch", message)
logにエラーが大量に出ています

2024-04-03 15:18 UTC, dsato80 commented on common.py
> +        if event.subtype not in ["next", "arrived", "content", "sound", "getlanguage", "stop-reason"]:
これは消すんですよね？

2024-04-04 01:02 UTC, miyazakifuki commented on common.py
> +    activity_log("cabot/touch", message)
logに大量に出ていたエラーはこれが原因だったんですね…

2024-04-04 01:43 UTC, daisukes commented on common.py
> +    activity_log("cabot/touch", message)
これとrosmapがエラーを出していました。

2024-04-04 03:01 UTC, miyazakifuki commented
すみません、確認なのですが、サブモジュールの更新はまた別でブランチ切ってPR出した方が良いですか？(このPRにcommitを入れるのは良くないですか？)

2024-04-04 03:11 UTC, dsato80 requested changes
すいません、特に理由がなければactivity_log自体を取り除く方向でお願いします

2024-04-04 03:11 UTC, dsato80 commented on common.py
> +    activity_log("cabot/touch", str(message))
先にこのactivity_logが必要かどうかという話をすべきでしたね
基本的にcabot/eventのトピックと同じなので、activity_logには出さなくて良い気がします。

2024-04-04 03:13 UTC, dsato80 commented
> すみません、確認なのですが、サブモジュールの更新はまた別でブランチ切ってPR出した方が良いですか？(このPRにcommitを入れるのは良くないですか？)

中身によります。
このPRに関連するなら入れたら良いと思います。

2024-04-04 03:21 UTC, miyazakifuki commented
> すいません、特に理由がなければactivity_log自体を取り除く方向でお願いします

承知しました。

> 中身によります。
このPRに関連するなら入れたら良いと思います。

本当はrecover-hci0の時に入れるべきだったのですが、サブモジュールに関してまだわかっていなかった時でしたので、、
後で別PRにします。

また、このPRのcommitも`send touch to app`に統一します

2024-04-04 03:30 UTC, dsato80 approved these changes
LGTM

2024-04-04 03:31 UTC, merged